# Generated by Django 5.1.5 on 2025-03-28 14:51

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=20, null=True)),
                ('Key', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_super',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('postid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, primary_key=True, serialize=False)),
                ('pheading', models.CharField(max_length=100)),
                ('pdescription', models.TextField(blank=True, max_length=2000)),
                ('pimage', models.ImageField(upload_to='static/post_image')),
                ('pfile', models.FileField(upload_to='static/post_file/')),
                ('pdate', models.DateField(auto_now_add=True)),
                ('ptime', models.TimeField(auto_now_add=True)),
                ('pcreated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super.tbl_register')),
                ('plike', models.ManyToManyField(related_name='likes', to='Super.tbl_register')),
            ],
        ),
    ]
