# Generated by Django 5.1.5 on 2025-03-30 08:14

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pfile',
            field=models.FileField(blank=True, upload_to='static/post_file/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pimage',
            field=models.ImageField(blank=True, upload_to='static/post_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='tbl_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcomment', models.CharField(max_length=100)),
                ('pcomment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super.tbl_register')),
                ('pcomment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super.post')),
            ],
        ),
    ]
